#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 contributors
# SPDX-License-Identifier: Apache-2.0
"""Refuse an absolute home directory path in a tracked file.

This repository is public. An absolute path from the machine that produced a file carries the
local username, and once it is pushed it stays in the history whether or not the file is later
fixed -- so the only cheap moment to catch it is before the commit lands.

The check exists because it already failed once: an extraction artifact generated by a script that
printed the path it was given shipped a home directory path to a public repository, twice, and the
review that merged it did not see it. A generator that prints its input path will do this again;
the gate is what makes that a CI failure rather than a discovery months later.

Scope is tracked files only -- untracked and gitignored paths (eval `results/`, local scratch) are
not published and are not this check's business.

Two things are not leaks and pass:

  * a placeholder, meaning the path contains < or > -- /Users/<user>/ is documentation
  * one of the fictional user names in FICTIONAL below, which the test fixtures and skill examples
    use on purpose

A real user name is anything else, and adding one to FICTIONAL is a deliberate act that shows up in
review -- which is the point. A line may also carry `private-path-ok` with a reason beside it.

Exit 0 clean / 1 findings / 2 error.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys

HOME_PATH = re.compile(r"/(?:Users|home)/(?!<)([A-Za-z0-9_][A-Za-z0-9_.-]*)/")
PLACEHOLDER = re.compile(r"[<>]")
OPT_OUT = "private-path-ok"

# Names used deliberately in fixtures, examples and documentation. Not people.
FICTIONAL = frozenset(
    {"alice", "bob", "carol", "dev", "example", "me", "rjmiller", "runner", "user", "you"}
)
SKIP_SUFFIXES = (".png", ".jpg", ".jpeg", ".gif", ".pdf", ".ico", ".zip", ".gz")


def tracked_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], capture_output=True, text=True, check=True
    ).stdout
    return [p for p in out.split("\0") if p and not p.endswith(SKIP_SUFFIXES)]


def scan(paths: list[str]) -> list[tuple[str, int, str]]:
    findings = []
    for path in paths:
        try:
            with open(path, encoding="utf-8", errors="strict") as fh:
                lines = fh.readlines()
        except (UnicodeDecodeError, OSError):
            continue  # binary or unreadable: not a text leak this check can judge
        for n, line in enumerate(lines, 1):
            if OPT_OUT in line:
                continue
            for m in HOME_PATH.finditer(line):
                if PLACEHOLDER.search(m.group(0)):
                    continue
                if m.group(1).lower() in FICTIONAL:
                    continue
                findings.append((path, n, m.group(0)))
    return findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("paths", nargs="*", help="files to check (default: all tracked files)")
    args = parser.parse_args(argv)

    try:
        paths = args.paths or tracked_files()
    except (subprocess.CalledProcessError, OSError) as exc:
        print(f"cannot list tracked files: {exc}", file=sys.stderr)
        return 2

    findings = scan(paths)
    for path, n, hit in findings:
        print(f"{path}:{n}: absolute home path {hit!r} - use the file name, ~ or a <placeholder>")
    if findings:
        print(
            f"\n{len(findings)} absolute home path(s) in tracked files. This repository is public.",
            file=sys.stderr,
        )
        return 1
    print(f"OK: {len(paths)} tracked files, no absolute home paths")
    return 0


if __name__ == "__main__":
    sys.exit(main())
