#!/usr/bin/env python3
# Copyright 2026 contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""
gen_replay.py — generate a libusb1 replay script from decoded transfers.

Takes a protocol-hypothesis JSON (from infer_commands.py) and a decoded
capture JSON (from decode.py) and emits a runnable Python script that opens
the device and replays the observed traffic.

Usage:
    python3 gen_replay.py hypothesis.json capture.json -o replay.py
    python3 gen_replay.py hypothesis.json capture.json  # prints to stdout
"""

import argparse
import json
from pathlib import Path
from typing import List


# ---------------------------------------------------------------------------
# Template rendering
# ---------------------------------------------------------------------------

_HEADER = '''\
#!/usr/bin/env python3
"""
Replay script — auto-generated by cynthion-reverse-engineer gen_replay.py
Device: {vid} / {pid}

Prerequisites:
    pip install libusb1          # primary
    pip install pyusb            # alternative fallback (see below)

On macOS/Linux, you may need to run with sudo, or set up udev rules.
"""

import sys
import time

# --- libusb1 (primary) ---
try:
    import usb1
    _USE_LIBUSB1 = True
except ImportError:
    _USE_LIBUSB1 = False

# --- pyusb (fallback) ---
if not _USE_LIBUSB1:
    try:
        import usb.core
        import usb.util
    except ImportError:
        sys.exit("Neither libusb1 nor pyusb found. Install one:\\n  pip install libusb1")

VID = {vid_int}
PID = {pid_int}
TIMEOUT_MS = 2000


def open_device_libusb1():
    ctx = usb1.USBContext()
    handle = ctx.openByVendorIDAndProductID(VID, PID)
    if handle is None:
        sys.exit(f"Device {{VID:#06x}}:{{PID:#06x}} not found. Is it plugged in?")
    return ctx, handle


def open_device_pyusb():
    dev = usb.core.find(idVendor=VID, idProduct=PID)
    if dev is None:
        sys.exit(f"Device {{VID:#06x}}:{{PID:#06x}} not found. Is it plugged in?")
    dev.set_configuration()
    return dev


'''

_CONTROL_LIBUSB1 = '''\
    # Control transfer: {desc}
    # bmRequestType={bm:#04x} bRequest={req:#04x} wValue={wval:#06x} wIndex={widx} wLength={wlen}
    try:
        result = handle.controlRead(
            request_type={bm:#04x},
            request={req:#04x},
            value={wval:#06x},
            index={widx},
            length={wlen},
            timeout=TIMEOUT_MS,
        )
        print(f"ctrl IN  → {{len(result)}} bytes: {{result.hex()}}")
    except usb1.USBError as e:
        print(f"ctrl error: {{e}}")
'''

_CONTROL_OUT_LIBUSB1 = '''\
    # Control OUT: {desc}
    data = bytes.fromhex("{payload}")
    try:
        handle.controlWrite(
            request_type={bm:#04x},
            request={req:#04x},
            value={wval:#06x},
            index={widx},
            data=data,
            timeout=TIMEOUT_MS,
        )
        print("ctrl OUT  ✓")
    except usb1.USBError as e:
        print(f"ctrl error: {{e}}")
'''

_BULK_OUT_LIBUSB1 = '''\
    # Bulk OUT ep={endp} — {desc}
    data = bytes.fromhex("{payload}")
    try:
        n = handle.bulkWrite({ep_addr:#04x}, data, timeout=TIMEOUT_MS)
        print(f"bulk OUT ep={endp} → {{n}} bytes sent")
    except usb1.USBError as e:
        print(f"bulk OUT error: {{e}}")
'''

_BULK_IN_LIBUSB1 = '''\
    # Bulk IN ep={endp}
    try:
        resp = handle.bulkRead({ep_addr:#04x}, {length}, timeout=TIMEOUT_MS)
        print(f"bulk IN  ep={endp} ← {{len(resp)}} bytes: {{resp.hex()}}")
    except usb1.USBError as e:
        print(f"bulk IN error: {{e}}")
'''


def _bm_to_int(bm: str) -> int:
    return int(bm, 16)


def _hex_to_int(h: str, default: int = 0) -> int:
    try:
        return int(h.replace("0x", ""), 16)
    except (ValueError, AttributeError):
        return default


def _render_control(xfer: dict, interface: int) -> str:
    setup = xfer.get("setup", {})
    bm   = _bm_to_int(setup.get("bmRequestType", "0x00"))
    req  = setup.get("bRequest", 0)
    wval = _hex_to_int(setup.get("wValue", "0x0000"))
    widx = setup.get("wIndex", 0)
    wlen = setup.get("wLength", 0)
    direction = setup.get("direction", "OUT")
    desc = (xfer.get("decoded") or {}).get("descriptor_name") or f"req={req:#04x}"

    if direction == "IN":
        return _CONTROL_LIBUSB1.format(bm=bm, req=req, wval=wval, widx=widx, wlen=wlen, desc=desc)
    else:
        payload = xfer.get("payload_hex") or ""
        return _CONTROL_OUT_LIBUSB1.format(bm=bm, req=req, wval=wval, widx=widx, desc=desc, payload=payload)


def _render_bulk(xfer: dict) -> str:
    endp = xfer["endp"]
    direction = xfer["direction"]
    payload_hex = xfer.get("payload_hex") or ""
    desc = f"{len(payload_hex) // 2} bytes"

    if direction == "OUT":
        ep_addr = endp  # OUT endpoint
        return _BULK_OUT_LIBUSB1.format(endp=endp, ep_addr=ep_addr, payload=payload_hex, desc=desc)
    else:
        ep_addr = endp | 0x80  # IN endpoint
        length = xfer.get("payload_len") or 64
        return _BULK_IN_LIBUSB1.format(endp=endp, ep_addr=ep_addr, length=length)


def generate_replay(
    hypothesis: dict,
    transfers: List[dict],
    interface: int = 0,
    max_bulk: int = 20,
) -> str:
    dev = hypothesis.get("device", {})
    vid_str = dev.get("idVendor", "0x0000")
    pid_str = dev.get("idProduct", "0x0000")
    vid_int = _hex_to_int(vid_str)
    pid_int = _hex_to_int(pid_str)

    lines = [_HEADER.format(vid=vid_str, pid=pid_str, vid_int=vid_int, pid_int=pid_int)]

    # Enumeration replay (control transfers, filtered to key requests)
    control_xfers = [x for x in transfers
                     if x.get("type") == "control"
                     and x.get("endp", 0) == 0
                     and x.get("setup", {}).get("bRequest") in (
                         5,   # SET_ADDRESS (host handles this; skip in replay)
                         6,   # GET_DESCRIPTOR
                         9,   # SET_CONFIGURATION
                         10,  # SET_INTERFACE class request
                     )]

    # Main replay function (libusb1 path)
    lines.append("def replay_libusb1():")
    lines.append("    ctx, handle = open_device_libusb1()")
    lines.append(f"    handle.claimInterface({interface})")
    lines.append("    try:")
    lines.append(f"        # --- Replaying {len(control_xfers)} control transfers ---")

    for xfer in control_xfers:
        req = (xfer.get("setup") or {}).get("bRequest", 0)
        if req == 5:
            continue  # SET_ADDRESS is handled by the OS
        block = _render_control(xfer, interface)
        for line in block.splitlines():
            lines.append("        " + line)

    # Bulk/interrupt transfers
    bulk_xfers = [x for x in transfers if x.get("type") != "control"][:max_bulk]
    if bulk_xfers:
        lines.append("")
        lines.append(f"        # --- Replaying up to {max_bulk} bulk/interrupt transactions ---")
        for xfer in bulk_xfers:
            block = _render_bulk(xfer)
            for line in block.splitlines():
                lines.append("        " + line)

    lines.append("    finally:")
    lines.append(f"        handle.releaseInterface({interface})")
    lines.append("        handle.close()")
    lines.append("        ctx.close()")
    lines.append("")

    # Entry point
    lines.append("if __name__ == '__main__':")
    lines.append("    if _USE_LIBUSB1:")
    lines.append("        replay_libusb1()")
    lines.append("    else:")
    lines.append("        sys.exit('pyusb fallback not yet implemented — install libusb1')")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(
        description="Generate a libusb1 replay script from a protocol hypothesis + capture."
    )
    p.add_argument("hypothesis", help="JSON from infer_commands.py")
    p.add_argument("capture", help="JSON from decode.py (the capture to replay)")
    p.add_argument("-o", "--output", help="Output file (default: stdout)")
    p.add_argument("--interface", type=int, default=0, metavar="N",
                   help="USB interface number to claim (default: 0)")
    p.add_argument("--max-bulk", type=int, default=20, metavar="N",
                   help="Max bulk transactions to include (default: 20)")
    args = p.parse_args()

    with open(args.hypothesis) as f:
        hypothesis = json.load(f)
    with open(args.capture) as f:
        transfers = json.load(f)

    script = generate_replay(hypothesis, transfers,
                              interface=args.interface, max_bulk=args.max_bulk)

    if args.output:
        Path(args.output).write_text(script)
        print(f"Written to {args.output}")
    else:
        print(script)


if __name__ == "__main__":
    main()
